### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by dsikes** [KunalKapadia/express-mongoose-es6-rest-api#10]
When running your code i get the following error:

        /express-mongoose-es6-rest-api/node_modules/kew/kew.js:198
              throw e
              ^
        TypeError: Path must be a string. Received undefined

I am working on figuring out what the problem is now, but thought I'd post it here so you would be aware of it.

I cloned it down, cd'd into it, ran NPM install,  and then DEBUG=express-mongoose-es6-rest-api:* npm start 

So, I am assuming there is some variable that isn't being set, because of the udefined. Still tracing it. I'll update this once I find something.

**Comment by dsikes** [comment]
![image](https://cloud.githubusercontent.com/assets/8764573/15729606/bcb88076-2833-11e6-8c24-f6b326dec050.png)


So, the issue that I found was inside of the gulp task on line 67. I am unsure what is causing the error, because if I remove that line, run it, it works... then I can add that line back, run it, and it still works. But trying to run it, while the dist directory is empty, it fails. So, I am not sure what else you have got going on, but thought you'd want to get that fixed. Hope it helps.

**Comment by KunalKapadia** [comment]
@dsikes Can you let me know the node version you are using ?

**Comment by nylsoo** [comment]
@KunalKapadia running into the same problem. My node version is v6.2.0.

**Comment by dsikes** [comment]
@KunalKapadia I am running v6.2.0 as well. Thanks @nylsoo! About to try again after instlaling `path`.

**Comment by dsikes** [comment]
![image](https://cloud.githubusercontent.com/assets/8764573/15761939/04e4b242-28e9-11e6-98d8-6574fe46da9c.png)

The issue was **NOT** resolved by installing path. The error is being thrown in the `kew` package. @KunalKapadia  Could you try installing on Node 6.2.0 and seeing if you can duplicate the issue? I want to make sure its not something I'm doing wrong.

**Comment by nylsoo** [comment]
@dsikes Sorry, forgot to mention that i updated babel-core to 6.9.1. This removed the Path must be a tring error for me.

**Comment by KunalKapadia** [comment]
@nylsoo Thanks for the resolution. Updated [master](https://github.com/KunalKapadia/express-mongoose-es6-rest-api/commit/ba75dc203f9c34d9a09b0cc36f5113a2ea94acfb) branch
