### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by kunalkapadia** [kunalkapadia/express-mongoose-es6-rest-api#141]

**Comment by stefanwalther** [comment]
Hi @KunalKapadia, I very much like your boilerplate, just stopped with a similar effort I have started with and just looking how I can contribute.
Related to this issue, what is your thinking:

- Create e.g. a circle-ci job that runs all the tests and if successful create an image on docker-hub
- Or was it more about to spin up the dev-environment using mongoose?

I am interested in both, having that in a boilerplate, so I might work on both.

**Comment by KunalKapadia** [comment]
@stefanwalther Would soon be integrating Docker which will serve both the above use cases. On CI, it'll create a image, spawn a container with that images where it'll install dev dependencies and run test cases. I have already started working on this. Would add you as reviewer on the PR.

Please let me know if you have any more feedback on this. Also please feel free to contribute to other issues on the project.

**Comment by stefanwalther** [comment]
Great! Happy to help ...
