### ISSUE TITLE
Serving Static Assets Fails

### ISSUE THREAD

**Issue by ajainvivek** [KunalKapadia/express-mongoose-es6-rest-api#149]
How can I serve static files from current working directory. I have added public folder in root and it doesn't serve

```
app.use('/static', () => {
  let cwd = path.join(process.cwd());
  let staticfiles = path.resolve(cwd, 'public');
  return express.static(staticfiles);
});
```

**Comment by KunalKapadia** [comment]
@ajainvivek Please refer https://expressjs.com/en/starter/static-files.html for static assets.

**Comment by ajainvivek** [comment]
I got it fixed. Thanks mate 👍

**Comment by duard** [comment]
@ajainvivek please, post your solution for this.

**Comment by selmi-karim** [comment]
same problem, @ajainvivek  post your solution for this please.
