### ISSUE TITLE
Istanbul issue in Windows

### ISSUE THREAD

**Issue by wassimz** [KunalKapadia/express-mongoose-es6-rest-api#151]
Hi,

When run the test script, I got the same error as [here](https://github.com/gotwarlost/istanbul/issues/677).
I am running under windows (node v5).

Any hint to solve it ?

**Comment by KunalKapadia** [comment]
@wassimz Can you try this npm test cmd
`"test": "NODE_ENV=test babel-node node_modules/.bin/isparta cover node_modules/mocha/bin/_mocha -- --ui bdd --reporter spec --colors --compilers js:babel-core/register ./server/**/*.test.js"`

I have just replaced `_mocha` with `node_modules/mocha/bin/_mocha`

**Comment by wassimz** [comment]
@KunalKapadia 

Yes I have already tried and still getting the same issue exception. Below is what I am getting:

> SET NODE_ENV=test & babel-node node_modules/.bin/isparta cover node_modules/mocha/bin/_mocha -- --ui bdd
 --reporter spec --colors --compilers js:babel-core/register ./server/**/*.test.js
> G:\Code\Project-Test\node_modules\.bin\isparta:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (G:\Code\Java\QMIC\Beacons\Back-End\Proximi
ty-Firebase\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at G:\Code\Project-Test\node_modules\babel-cli\lib\_babel-node.js:159
:24
    at Object.<anonymous> (G:\Code\Java\QMIC\Beacons\Back-End\Proximity-Firebase\node_modules\babel-cli\li
b\_babel-node.js:160:7)
    at Module._compile (module.js:425:26)

**Comment by KunalKapadia** [comment]
@wassimz Can you try the same with node v4 or node v6. As v6 is the LTS version right now ?

**Comment by wassimz** [comment]
OK I will try to install the v6 and I will keep informed. Thanks

**Comment by wassimz** [comment]
@KunalKapadia 

I have tried with the latest LTS version (6.9.1) and still get the same issues.

**Comment by Altiano** [comment]
same issue

**Comment by delsner** [comment]
I created a PR for this issue #205
