### ISSUE TITLE
Cant run tests on windows

### ISSUE THREAD

**Issue by vincaslt** [KunalKapadia/express-mongoose-es6-rest-api#160]
Running `yarn test` I am getting an error saying that NODE_ENV is not recognized as a command. The line which is being run: `NODE_ENV=test babel-node node_modules/.bin/isparta cover _mocha -- --ui bdd --reporter spec --colors --compilers js:babel-core/register ./server/**/*.test.js`

**Comment by wassimz** [comment]
Same issue as here #151

**Comment by vincaslt** [comment]
I've changed the line to `set NODE_ENV=test node_modules/.bin/babel-node node_modules/.bin/isparta cover _mocha -- --ui bdd --reporter spec --colors --compilers js:babel-core/register ./server/**/*.test.js`

Which now runs on windows, but it only says Executed in 0.07s and no output...

**Comment by KunalKapadia** [comment]
@vincaslt @wassimz I'll set up appveyor for testing on Windows #161
Please let me know you guys want to contribute to the same.

**Comment by wassimz** [comment]
@KunalKapadia 

It's fine for me.

**Comment by wassimz** [comment]
@vincaslt 
You have missed to add the "__&&__" after "__set NODE_ENV=test__"

**Comment by Altiano** [comment]
@wassimz I get this error then
![image](https://cloud.githubusercontent.com/assets/8316282/21091231/d06a4a3e-c07f-11e6-93a7-475f9956343c.png)

**Comment by wassimz** [comment]
@Altiano 
Yes this is the same error we got when running test on windows environment

**Comment by delsner** [comment]
I created a PR for this issue #205

**Comment by KunalKapadia** [comment]
@vincaslt @wassimz @Altiano @wassimz Closing this.
