### ISSUE TITLE
Gulp is starting twice

### ISSUE THREAD

**Issue by Altiano** [KunalKapadia/express-mongoose-es6-rest-api#172]
I don't know whether this is a intended or not but this is quite slow when on development.
*You can produce the same result just by changing `/api/health-care` response text from `OK` to anything
Any Solution?

![image](https://cloud.githubusercontent.com/assets/8316282/20955951/e1ecca72-bc81-11e6-884f-5c9248bed33a.png)

**Comment by KunalKapadia** [comment]
@Altiano I tried to reproduce this, but for me it restarted only once. May be you made changes and saved twice ?

**Comment by Altiano** [comment]
well, it always happens if I use atom, what text editor do you use?

**Comment by KunalKapadia** [comment]
@Altiano I use WebStorm, did you try with any other text editor ?

**Comment by Altiano** [comment]
I'll try it, thanks

**Comment by KunalKapadia** [comment]
@Altiano Closing this for now. Let me know if you have any more questions.

**Comment by James9074** [comment]
Hitting this issue myself. Not too sure what's going on here...
