### ISSUE TITLE
Server not refreshing correctly.

### ISSUE THREAD

**Issue by ditproz** [KunalKapadia/express-mongoose-es6-rest-api#173]
First time for using this package.  After following the install procedures, getting the server up, running and listening, I have tried to post a user to test the next step of the API...  The response I got was.... 
```

{
  "message": "\"mobileNumber\" with value \"07834368491\" fails to match the required pattern: /^[1-9][0-9]{9}$/",
  "stack": "Error: \"mobileNumber\" with value \"07834368491\" fails to match the required pattern: /^[1-9][0-9]{9}$/\n    at APIError.ExtendableError (E:\\napi\\dist\\server\\helpers\\APIError.js:35:11)\n    at new
```
Which is legitimate, however - even when I change the user model to the following:

```
const UserSchema = new mongoose.Schema({
  username: {
    type: String,
    required: true
  },
/*  mobileNumber: {
    type: String,
    required: true
  },*/
  createdAt: {
    type: Date,
    default: Date.now
  }
});

```

I still get the same error - this happens despite doing a clear restart of the server (which I think it does automatically anyway) or even the computer.  Any ideas would be greatly appreciated.  

Thanks

Dan

**Comment by KunalKapadia** [comment]
@ditproz That's because you are not getting error from mongoose schema. You are getting error from param validation https://github.com/KunalKapadia/express-mongoose-es6-rest-api/blob/develop/config/param-validation.js#L8

**Comment by ditproz** [comment]
Many thanks!
