### ISSUE TITLE
have problem in auth

### ISSUE THREAD

**Issue by ouzhou** [KunalKapadia/express-mongoose-es6-rest-api#184]
i find the user's CRUD don't have auth, i hope it have a permission control,  so that the administrator can handle the user instead of visitors

**Comment by simonschllng** [comment]
The default login user is hard coded into the auth module for demo. You
have to combine it with a user list yourself.

Am 15.12.2016 08:07 schrieb "欧舟" <notifications@github.com>:

**Comment by ouzhou** [comment]
@simonschllng ok, i understand .
by the way, i think the plugin del should using by  del.sync

**Comment by KunalKapadia** [comment]
@ouzhou Yes it should be `del.sync`. Will be updating it soon. Closing this for now. Thanks.
