### ISSUE TITLE
Pass req.body directly into mongoose model?

### ISSUE THREAD

**Issue by simonschllng** [KunalKapadia/express-mongoose-es6-rest-api#185]
I notice that this project reads every single parameter from `req.body` into a new object just to create the database instance from it. Example from _user.controller.js_:

````
function create(req, res, next) {
  const user = new User({
    username: req.body.username,
    mobileNumber: req.body.mobileNumber
  });

  user.save()
    .then(savedUser => res.json(savedUser))
    .catch(e => next(e));
}
````

Is there a reason for that? Why not simply to `new User(req.body)`?

**Comment by KunalKapadia** [comment]
@simonschllng `req.body` can have params that may not be the field of user. No particular reason other than this, basically boils down to personal preferences.

**Comment by markxxv** [comment]
> @simonschllng

For some reason exists models right? So why you should duplicate model fields in controller? It's stupid monkey work. The model must ignore params that not present. Otherwise there’s  a trouble understanding the architecture.

Look example in Laravel:

```
$user = User::create($request->all());
```
