### ISSUE TITLE
Protected route

### ISSUE THREAD

**Issue by cloud-tribal** [KunalKapadia/express-mongoose-es6-rest-api#219]
What makes this a protected route ?
```
/**
 * This is a protected route. Will return random number only if jwt token is provided in header.
 * @param req
 * @param res
 * @returns {*}
 */
function getRandomNumber(req, res) {
  // req.user is assigned by jwt middleware if valid token is provided
  return res.json({
    user: req.user,
    num: Math.random() * 100
  });
}
```

**Comment by KunalKapadia** [comment]
@cloud-tribal We are using `expressJwt` middleware [here](https://github.com/KunalKapadia/express-mongoose-es6-rest-api/blob/develop/server/routes/auth.route.js#L17) for this route, which will verify the json token before execution goes into route handler.
