### ISSUE TITLE
No coverage information was collected

### ISSUE THREAD

**Issue by erwin16** [KunalKapadia/express-mongoose-es6-rest-api#239]
Hi there , thanks for this awesome boilerplate ! I'm discovering it step by step...
running

`yarn test:check-coverage`

is passing all tests correctly , but stating: 

`No coverage information was collected. Exit without writing coverage information`
`Done in 9.89s.
ERROR: No coverage files found.
error Command failed with exit code 1.
`

How code coverage is handle exactly ?  do we need to add istanbul package to run correctly the test:check-covergae script ?

``

**Comment by erwin16** [comment]
SOLVED !

Need to install istanbul version 1.0.0-alpha.2
`yarn add istanbul@1.0.0-alpha.2 --dev`

and run the script. istanbul/lib/cli.js in package.json

`"test-istanbul": "cross-env NODE_ENV=test babel-node ./node_modules/istanbul/lib/cli.js cover node_modules/mocha/bin/_mocha -- --ui bdd --reporter spec --colors --compilers js:babel-core/register ./server/**/*.test.js"`

mocha tests pass and coverage is performed ...

**Comment by simonschllng** [comment]
Is this missing in the documentation/readme?
