### ISSUE TITLE
express validation on param converter

### ISSUE THREAD

**Issue by sergio11** [KunalKapadia/express-mongoose-es6-rest-api#25]
Hi,

How I can use validation in a param converter?
I wanted to use Joi.objectId () to validate that this is a mongodb valid id

```
router.route('/:id')
  /** GET /api/users/:userId - Get user */
  .get(validate(paramValidation.get),userCtrl.get)

  /** PUT /api/users/:userId - Update user */
  .put(validate(paramValidation.updateUser), userCtrl.update)

  /** DELETE /api/users/:userId - Delete user */
  .delete(validate(paramValidation.deleteUser), userCtrl.remove);

/** Load user when API with userId route parameter is hit */
router.param('id', userCtrl.load);
```

Thanks and regards

**Comment by KunalKapadia** [comment]
Hi @sergio11 

You can validate mongo id like this.
You have to this for each api validation having `id` in the API path as this cannot be done directly with param converter.

```
  param: {
      id: Joi.objectId()
  }
```

**Comment by sergio11** [comment]
Thanks for answering.
As you say, I am validating on each endpoint the param id.

```
updateUser: {
    body: {
      fullname: Joi.string().required(),
      username: Joi.string().required(),
      password: Joi.string().regex(/^[a-zA-Z0-9]{5,30}$/),
      website: Joi.string().optional(),
      biography: Joi.string().optional(),
      email: Joi.string().email(),
      mobileNumber: Joi.string().regex(/^[1-9]{9}$/).required()
    },
    params: {
      userId: Joi.objectId()
    }
  }
```

The problem is that the param converter runs before and causes the following error when I provide an invalid _id (/api/users/dsadas232):

**CastError: Cast to ObjectId failed for value "dsadas232" at path "_id"**

I am looking forward to your response. regards

**Comment by KunalKapadia** [comment]
@sergio11 It should be `id: Joi.objectId()`. Can you try with this change ?

**Comment by sergio11** [comment]
I've already changed it and I still get the same error.

**Comment by KunalKapadia** [comment]
@sergio11 oh sorry. **CastError: Cast to ObjectId failed for value "dsadas232" at path "_id"** is actually valid errors. Trying using `/api/users/57a3079225028ce79705e88b` and you won't get the error. 

http://stackoverflow.com/questions/13850819/can-i-determine-if-a-string-is-a-mongodb-objectid
