### ISSUE TITLE
Error: API not found at APIError.ExtendableError

### ISSUE THREAD

**Issue by i2joseph** [KunalKapadia/express-mongoose-es6-rest-api#26]
Help. I just clone it and run it and got this error below. Please help. Thanks.
Error: API not found at APIError.ExtendableError

{"message":"Not Found","stack":"Error: API not found\n    at APIError.ExtendableError (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/dist/server/helpers/APIError.js:35:11)\n    at new APIError (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/dist/server/helpers/APIError.js:63:77)\n    at /Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/dist/config/express.js:122:13\n    at Layer.handle [as handle_request] (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:312:13)\n    at /Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:330:12)\n    at next (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:271:10)\n    at Layer.handle [as handle_request] (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/layer.js:91:12)\n    at trim_prefix (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:312:13)\n    at /Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:330:12)\n    at next (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:271:10)\n    at /Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express-winston/index.js:291:9\n    at Layer.handle [as handle_request] (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:312:13)\n    at /Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:330:12)\n    at next (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/express/lib/router/index.js:271:10)\n    at cors (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/cors/lib/index.js:178:7)\n    at /Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/cors/lib/index.js:228:17\n    at originCallback (/Users/joseph/Documents/node-heroku/express-mongoose-es6-rest-api/node_modules/cors/lib/index.js:217:15)"}

Node v6.3.1
NPM v3.10.3

**Comment by tutts** [comment]
try going to `http://localhost:3000/api/health-check`

**Comment by i2joseph** [comment]
@tutts gave me result OK. But I am still getting this error. Thanks.

**Comment by i2joseph** [comment]
I found the problem. Sorry my mistake. Thanks.

**Comment by cbgrasshopper** [comment]
What was the problem & solution?

**Comment by laumair** [comment]
@cbgrasshopper If you are facing the same problem, I believe the mistake you are making is skipping `/api`, so instead of hitting `localhost:3000/users` you should be doing `localhost:3000/api/users`. Hope that helps.

**Comment by volynchuk18** [comment]
None of these solutions suited me. Can I get help?

**Comment by DarkSmile92** [comment]
Having the same issue right now..

**Comment by zuest** [comment]
for my case it was http://localhost:4040/api/health-check
