### ISSUE TITLE
Getting Mongoose Promise deprecation warning when running test

### ISSUE THREAD

**Issue by Ebsy** [KunalKapadia/express-mongoose-es6-rest-api#266]
Getting the 'infamous' Mongoose warning when running the test.

**DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html**

Tried to use mongoose.Promise = require('bluebird') in user.test.js but still getting the warning.

**Comment by simonschllng** [comment]
Good point! Didn't know that this project still uses mpromise! Thanks for pointing it out.

**Comment by Ebsy** [comment]
Is there an 'easy' fix for this Simon? Looking through the updates, I thought this was fixed by assigning the global ES6 promise to mongoose.Promise

**Comment by KunalKapadia** [comment]
@Ebsy Can you please attach a screenshot for the same ?
Also can you take the latest code before running tests ?

**Comment by Ebsy** [comment]
Hi @KunalKapadia, my mistake after all. I updated mongoose to 4.8.1 and got the warning in 'npm test' at the user API POST. if I downgrade back to 4.7.7 as released, I no longer get the warning. There's an issue open on the mongoose repo - https://github.com/Automattic/mongoose/issues/4951 I'll keep an eye on it, thanks. I'll close this now (and I'll try and remember not to upgrade packages before testing next time ;))
