### ISSUE TITLE
API Authentication using jsonwebtoken

### ISSUE THREAD

**Issue by KunalKapadia** [KunalKapadia/express-mongoose-es6-rest-api#27]

**Comment by cyrilchapon** [comment]
Some pieces of information to maybe help :

- The base [spec](http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html)
- An implementation by myself, inpired by [this one](https://thesabbir.com/how-to-use-json-web-token-authentication-with-sails-js/). It works under sails.js, but if one abstracts the MVC logic, he might understand the process :
  - [config and strategies definition](https://github.com/cyrilchapon/exia-secu-demo-api/blob/master/config/passport.js)
  - [token creation and password hashing](https://github.com/cyrilchapon/exia-secu-demo-api/blob/master/api/models/User.js)
  - [auth checking policy for protected routes](https://github.com/cyrilchapon/exia-secu-demo-api/blob/master/api/policies/tokenAuth.js)
  - [signin](https://github.com/cyrilchapon/exia-secu-demo-api/blob/master/api/controllers/AuthController.js)

The last follow this flow :
![jwt auth flow](https://camo.githubusercontent.com/ae3fdf60d160c458d7da470b1aaa0b1a90ab302d/687474703a2f2f626c6f672e627261696e6174746963612e636f6d2f636f6e74656e742f696d616765732f323031352f31312f6a77745f666c6f772e706e67)

**Comment by KunalKapadia** [comment]
@cyrilchapon Added support for jwt authentication.
