### ISSUE TITLE
Env vars

### ISSUE THREAD

**Issue by fcpauldiaz** [KunalKapadia/express-mongoose-es6-rest-api#274]
How can I config env vars with dotenv or similar package?

**Comment by KunalKapadia** [comment]
Hi @fcpauldiaz

I am planning to move to [node-config](https://github.com/lorenwest/node-config) for configuration management, please suggest your views on this.

**Comment by DangelZM** [comment]
Hello @KunalKapadia and @fcpauldiaz

Related to [https://12factor.net/config](https://12factor.net/config) 

I think better use **.env** example files for environments(.env.example, ...), instead to have config in files in /config/env/ folder. And add **.env** in to **.gitignore**. 
So you will have ability to configure you environment without making changes in code. 

And If you will use docker for deployment process, this can help you with deploy on some cloud system like AWS.

**Comment by fcpauldiaz** [comment]
Hello @KunalKapadia.

I support @DangelZM statement. It would be easier if there is only one environment file (.env) to config the application instead of multiple config files.

**Comment by KunalKapadia** [comment]
@fcpauldiaz @DangelZM Definitely moving away from current config files. Now question is whether to use [node-config](https://github.com/lorenwest/node-config) or [.env](https://github.com/motdotla/dotenv), will evaluate both of them and get back here. Meanwhile it'd be great if you can explore [node-config](https://github.com/lorenwest/node-config) and share your thoughts on the same.
