### ISSUE TITLE
Question - How to Have Tests in Nested Folders?

### ISSUE THREAD

**Issue by peterkrieg** [KunalKapadia/express-mongoose-es6-rest-api#303]
Tests only run if files are flat in the `server/tests` directory.

Minimum steps to reproduce:  

1.  create `auth` folder inside `server/tests`
2.  move `auth.test.js` to inside the `auth` folder
3.  run `yarn test` at root directory of project, and auth tests don't run

Anyone know how to allow for nested tests folders, and have all tests still run?

**Comment by KunalKapadia** [comment]
@peterkrieg Have updated npm tasks to consider nested tests file.

**Comment by peterkrieg** [comment]
@KunalKapadia Thanks so much for the quick response and change!
