### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by tluanga** [KunalKapadia/express-mongoose-es6-rest-api#32]
{"message":"Not Found","stack":"Error: API not found\n    at APIError.ExtendableError (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\dist\\server\\helpers\\APIError.js:35:11)\n    at new APIError (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\dist\\server\\helpers\\APIError.js:63:77)\n    at d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\dist\\config\\express.js:122:13\n    at Layer.handle [as handle_request] (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:312:13)\n    at d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:280:7\n    at Function.process_params (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:330:12)\n    at next (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:271:10)\n    at Layer.handle [as handle_request] (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\layer.js:91:12)\n    at trim_prefix (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:312:13)\n    at d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:280:7\n    at Function.process_params (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:330:12)\n    at next (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:271:10)\n    at d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express-winston\\index.js:291:9\n    at Layer.handle [as handle_request] (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:312:13)\n    at d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:280:7\n    at Function.process_params (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:330:12)\n    at next (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\express\\lib\\router\\index.js:271:10)\n    at cors (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\cors\\lib\\index.js:178:7)\n    at d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\cors\\lib\\index.js:228:17\n    at originCallback (d:\\Dev\\express-mongoose-es6-rest-api-master\\server1\\node_modules\\cors\\lib\\index.js:217:15)"}

**Comment by KunalKapadia** [comment]
@tluanga 
Can you please let me know what API are you hitting ?

**Comment by tluanga** [comment]
its working.. thans..
Can you please make an extensive tutorial and documentation for beginners just like me. I want to use this for my project

**Comment by KunalKapadia** [comment]
@tluanga README has all the steps required to work with the project.

**Comment by aravindhkm** [comment]
@tluanga pls let me know. how to fix this issue?
