### ISSUE TITLE
Great workflow to develop

### ISSUE THREAD

**Issue by dguard** [KunalKapadia/express-mongoose-es6-rest-api#34]
Hello,
I am using express-mongoose-es6-rest-api to build my REST API,
thanks for the product I am very like it!

But issue that it requires enough time to me to debug any error while development and write code for next feature

My workflow is:
1. Run npm start with nodemon in one console
2. Run npm test in other console (with nodemon, nodemon /usr/bin/gulp test)
3. I write one test for feature and I expect the test to be not passed (red)
4. I do one small change and see - test is passed (green) or still red
5. If test is still red then I change my code again until the test becomes green
6. When test is green then I repeat 3-6 steps for next feature

The issue is that each time when I change my code it requires >=7 seconds to get javascript code from source (clean, link, copy, babel) (1) and also >=3 seconds to run tests (2). It is >=10 seconds total per iteration. So just to change one word in my code or add one space I need to wait within 10 seconds each time. I can disable link task while development and run it before commit only but (1) task still requires >=4 seconds and it is not enough fast

Could you offer me best approach or workflow to debug and develop?

**Comment by petergombos** [comment]
Same issue here, unfortunately current setup is not ideal for TDD.

**Comment by laumair** [comment]
+1 for this. I think too this should be made more optimized.

**Comment by KunalKapadia** [comment]
@dguard @petergombos @laumair Can you try `npm run test:watch` now ?
It should just work in fraction of sec. Please let me know if this satisfies your requirement.

**Comment by KunalKapadia** [comment]
@dguard @petergombos @laumair Guys it'll be great if you can test and let me know your feedback So that I can close this one.
