### ISSUE TITLE
util module in index.js

### ISSUE THREAD

**Issue by EnergeticPixels** [KunalKapadia/express-mongoose-es6-rest-api#342]
Kapadia,

   I noticed in line two of your index.js (root project level) that you list 'util' as a module.  Further down in that file, I see where you use it.  But looking at your package.json (manifest file), I don't see it listed anywhere.  I do know that there is a gulp-util and a util on npm.  Which module did you intend?

respectfully,
Anthony

**Comment by osahner** [comment]
https://nodejs.org/api/util.html

**Comment by EnergeticPixels** [comment]
My apologies. Old man, gray hair moment.  Thank you for the reminder.
