### ISSUE TITLE
gulp not found (deploying)

### ISSUE THREAD

**Issue by dekkofilms** [kunalkapadia/express-mongoose-es6-rest-api#375]
I'm a little new to the whole deployment process, and really just wanted to ask best practices. I am deploying this to AWS, and in the logs I keep getting the error that the gulp command wasn't found. I know that in AWS it is only running the npm install --production flag. I read that some people move there devDependencies into the dependencies tree. Is this best practice? Is there a better way to do this?

Any advice or help would be greatly appreciated!

**Comment by BhattaRj** [comment]
Same here

**Comment by simonschllng** [comment]
In many projects, gulp is expected to be globally installed (npm install -g).

**Comment by oodgaard** [comment]
The README does say how to start your app in production.

# Use any process manager to start your services
4. pm2 start dist/index.js
