### ISSUE TITLE
Heroku deployemnt steps 

### ISSUE THREAD

**Issue by GeekRishabh** [kunalkapadia/express-mongoose-es6-rest-api#420]
Please add steps for deploying on heroku .
Getting alot of issue while hosting .

**Comment by nhim175** [comment]
A few things I need to do in order to deploy to Heroku
## 1. Change in `package.json` 
from 
```
"start": "gulp serve"
```
to
```
"dev": "gulp serve",
"start": "node index.js",
```
Reason: heroku will run `npm start` to start the app
For dev: `yarn start` will be `yarn run dev`

## 2. Change in `gulpfile.babel.js`
from
```
del.sync(['dist/**', 'dist/.*', 'coverage/**', '!dist', '!coverage'])
```
to
```
del.sync(['dist/**', 'dist/.*', '!dist/.git', '!dist/.git/**', 'coverage/**', '!dist', '!coverage'])
```
Reason: In order to deploy `/dist` to Heroku, `/dist` should be a heroku's git repo.

## 3. Deploy to Heroku manually
```bash
cd ./dist
git init
heroku git:remote -a app-name
git commit -am 'Init'
git push heroku master
```

or using `buildcontrol` to automate it.

**Comment by CheeKeatSong** [comment]
```
2018-01-25T14:59:17.015251+00:00 app[web.1]: > node index.js
2018-01-25T14:59:17.015253+00:00 app[web.1]:
2018-01-25T14:59:17.549902+00:00 app[web.1]: /app/config/config.js:35
2018-01-25T14:59:17.549917+00:00 app[web.1]:   throw new Error('Config validation error: ' + error.message);
2018-01-25T14:59:17.549921+00:00 app[web.1]: Error: Config validation error: child "JWT_SECRET" fails because ["JWT_SECRET" is required]
```
I followed your steps and I got this error. Can you please tell me why?

**Comment by selmi-karim** [comment]
same here. any solution guys ?

**Comment by ssurabhi10** [comment]
These are the steps for deploying code on heroku, where PROVIDER is heroku. (Use 'heroku' in place of PROVIDER).  Run these steps in terminal one by one.


git config --global user.name $GIT_USER_NAME

git config --global user.email $GIT_USER_EMAIL

# Install the Heroku gem (or the Heroku toolbelt)
gem install $PROVIDER

# Add your Heroku git repo:
git remote rm $PROVIDER ;

git remote add $PROVIDER git@$PROVIDER.com:$PROVIDER_APP_NAME.git ;

# Add your Heroku API key:
export HEROKU_API_KEY=$HEROKU_API_KEY

# Turn off warnings about SSH keys:
echo "   Host heroku.com" >> ~/.ssh/config

echo "   StrictHostKeyChecking no" >> ~/.ssh/config

echo "   CheckHostIP no" >> ~/.ssh/config

echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config

# Clear your current Heroku SSH keys:
$PROVIDER keys:clear

# Add a new SSH key to Heroku
yes | $PROVIDER keys:add

git add dist/ ;

git checkout -b $NEW_BRANCH ;

git commit -m "$COMMIT_MESSAGE" ;

# Push to Heroku
yes | git push --force $PROVIDER $NEW_BRANCH:$PROVIDER_BRANCH;

**Comment by geekrishabh** [comment]
Figured Out an Year Ago
