### ISSUE TITLE
Debugging in Chrome

### ISSUE THREAD

**Issue by priteshjha4u** [KunalKapadia/express-mongoose-es6-rest-api#422]
Hi, i am trying to debug this boilerplate application code on chrome developer tool. but it seems even after adding the port *(on which the application is running, 4040)* to network targets *(we can add in chrome at   [chrome://inspect](chrome://inspect) )* things are not working. after a bit of research i found that we must add `--inspect` flag when running the node server. now i am not sure exactly where i should add this flag in **package.json**.
Please suggest.
Thanks

**Comment by priteshjha4u** [comment]
I have figured it out. we can add `--inspect`  here
```
gulp.task('nodemon', ['copy', 'babel'], () =>
  plugins.nodemon({
    script: path.join('dist', 'index.js'), // put it here like 'dist/index.js --inspect'
    ext: 'js',
    ignore: ['node_modules/**/*.js', 'dist/**/*.js'],
    tasks: ['copy', 'babel']
  })
);
```

**Comment by wardnath** [comment]
For those who are trying to get debug working with Chrome as well, I changed:
```
script: path.join('dist', 'index.js'),
```
in gulpfile.babel.js

to 

```
exec: `node --inspect ${path.join('dist', 'index.js')}`,
```
