### ISSUE TITLE
Why I don't see my changes when I modify code

### ISSUE THREAD

**Issue by AlaeddineMessadi** [KunalKapadia/express-mongoose-es6-rest-api#457]
Hello guys, I just started a project, cloned the repo and run docker-compose

The app is up and running and get a response from `localhost:4040/api/health-check` although when I modify the code I don't see my changes.

Any suggestions please?

**Comment by okonon** [comment]
You need to rebuild Docker image and run that new version with your changes in it.

**Comment by AlaeddineMessadi** [comment]
Thank you @okonon for your answer, do you mean I have to rebuild the image each single change I make? 

Because in the `docker-compose.yml` file  Line 10  
says ` - .:/app` allowing you to modify the code without having to rebuild the image.

**Comment by okonon** [comment]
hmm maybe restart it then?

**Comment by AlaeddineMessadi** [comment]
I just installed `nodemon` to automatically restart the node application
