### ISSUE TITLE
I cant serve Any static file

### ISSUE THREAD

**Issue by alirezavalizade** [KunalKapadia/express-mongoose-es6-rest-api#52]
Im have image file in my public folder and added this code but it's not working : 
`
app.use("/public", express.static(path.join(__dirname, '/public')));
`

**Comment by laumair** [comment]
@alirezavalizade Where exactly have you added this? Can you show the whole file?

**Comment by ajainvivek** [comment]
How can I serve static files from current working directory. I have added public folder in root and it doesn't serve

```
app.use('/static', () => {
  let cwd = path.join(process.cwd());
  let staticfiles = path.resolve(cwd, 'public');
  return express.static(staticfiles);
});
```
