### ISSUE TITLE
gitignore OS files

### ISSUE THREAD

**Issue by laumair** [KunalKapadia/express-mongoose-es6-rest-api#55]
Hey, first of all great starter kit. 

I've recently started playing with it and its awesome. I looked into the `gitignore` file and there isn't mentioned any script for ignoring OS specific files. Are PRs welcomed? If you agree this, needs to be added I'd be more than happy to contribute.

**Comment by KunalKapadia** [comment]
@laumair Yes PRs are welcome :)

**Comment by laumair** [comment]
@KunalKapadia https://github.com/KunalKapadia/express-mongoose-es6-rest-api/pull/58 :)
