### ISSUE TITLE
Socket.io integration

### ISSUE THREAD

**Issue by laumair** [KunalKapadia/express-mongoose-es6-rest-api#59]
@KunalKapadia Ever planning on including optional socket.io?

**Comment by KunalKapadia** [comment]
@laumair Not sure if socket.io is a generic use case.
If we plan to include it, what example can we include as part of this boilerplate ?

**Comment by laumair** [comment]
@KunalKapadia I think we can make one. We can certainly design it in a way that those who want to use it built-in, great! Otherwise we will make it optional. We can certainly add some good implementation examples with some client side as well and I personally believe that would be a great plus.

**Comment by laumair** [comment]
Though this wouldn't be a small change. So, I think I want to be sure if we want to add it ATM. I am in progress of writing a sort of a wrapper service micro-lib for `react-redux` projects. Might be a good chance to basically use that an example.
