### ISSUE TITLE
nodemon watch does not trigger restart on change

### ISSUE THREAD

**Issue by iantanwx** [KunalKapadia/express-mongoose-es6-rest-api#8]
Tried with stock gulpfile, but making changes to the source folder doesn't cause nodemon to trigger dependent tasks and/or restart. Using node v5.8.0.

**Comment by quanganh206** [comment]
I think you forget start mongo

**Comment by KunalKapadia** [comment]
@iantanwx Can you please attach a screenshot ?
Is you `npm start` working fine ?

**Comment by quanganh206** [comment]
Yes, gulp also fine
