### ISSUE TITLE
Avoid duplicate file names for controllers, models & routes

### ISSUE THREAD

**Issue by hananwm** [KunalKapadia/express-mongoose-es6-rest-api#92]
consider renaming controllers, routes & models files by a naming convention.

user.controller.js
user.model.js
user.route.js

It makes the project navigation a lot easier

**Comment by KunalKapadia** [comment]
@hananwm Thanks for the suggestion. It has been incorporated. Please check. :)

**Comment by hananwm** [comment]
@KunalKapadia Awesome! keep up with the inspiring work!
